### ISSUE TITLE
sendtoaddress issue

### ISSUE THREAD

**Issue by pinpins** [NPW-Project/NewPowerCoin#4]
Hi,

My wallet http://explorer.npw.live:8080/address/NiCakGDXfarjepDtDsbAZf4EG7s4tWNvL2

getinfo
{
    "version": 1000000,
    "protocolversion": 70912,
    "walletversion": 61000,
    "balance": 1250.18066035,
    "zerocoinbalance": 0,
    "blocks": 12517,
    "timeoffset": 0,
    "connections": 16,
    "proxy": "",
    "difficulty": 159.73341204025,
    "testnet": false,
    "moneysupply": 8053697.5774572,
    "zNPWsupply": {
        "1": 0,
        "5": 0,
        "10": 0,
        "50": 0,
        "100": 0,
        "500": 0,
        "1000": 0,
        "5000": 0,
        "total": 0
    },
    "keypoololdest": "2018-06-02 08:26:43 +0300",
    "keypoolsize": 1001,
    "paytxfee": 0,
    "relayfee": 0.0001,
    "staking status": "Staking Not Active",
    "errors": ""
}

sendtoaddress NLXXYCpuUg6cfT3L1TKd4abSBURK4tu1Dm 100
error -4: insufficient funds.

Can you please check what is a problem here?

**Comment by normanx** [comment]
Please try ： sendtoaddress "NLXXYCpuUg6cfT3L1TKd4abSBURK4tu1Dm" 100
address need been quote in double quote

**Comment by pinpins** [comment]
It does not work either. I was able to send coins before without quotes, but at certain level it stops. Are immature coins added to getinfo balance?

**Comment by normanx** [comment]
Use follow command to check all confirmed balance, If there hasn't enough confirmed balanced, send will get "error -4: insufficient funds." error notice.

getbalance "*" 6
