### ISSUE TITLE
How to use the wallet in linux without GUI

### ISSUE THREAD

**Issue by LeaFZ96** [NPW-Project/NewPowerCoin#5]
I want to run the wallet on my vps, but I can not find any information about the shell command.

Or it's can not be used without Qt?

**Comment by normanx** [comment]
Of course you can run wallet on linux without GUI, use npwd to start daemon in background. For more information you can use "npwd --help" to get params and detail information about these params.

**Comment by LeaFZ96** [comment]
I'll try it, thank you!
