### ISSUE TITLE
masternode question

### ISSUE THREAD

**Issue by pruly** [NPW-Project/NewPowerCoin#7]
Can masternode program running on the VULTR VPS of $3.5/month? I tried, but this program often interrupts automatically.Can I enter some commands to solve this problem?

**Comment by normanx** [comment]
Master node can run on any vps with 512M+ meomory and enough HD space, I won't use VULTR and won't know system resource that vps provide, If the vps has 512M+ memory, you can try to change your system to Ubuntu 14 or 16. Ubuntu support all block chain project better than other Linux system.
